### ISSUE TITLE
Please update cpan module to latest :pray:

### ISSUE THREAD

**Issue by cateiru** [sekimura/text-markdown-discount#28]
[Text::Markdown::Discount on cpan](https://metacpan.org/dist/Text-Markdown-Discount) currently remains at 0.13.

The change that brought Discount to 2.2.7 has not yet been released and is not available. Could you please update the cpan module?

**Comment by sekimura** [comment]
0.14 has been uploaded https://metacpan.org/release/SEKIMURA/Text-Markdown-Discount-0.14

**Comment by cateiru** [comment]
@sekimura Thank you so much !!!
